### ISSUE TITLE
Space key not matched

### ISSUE THREAD

**Issue by Tails** [leojpod/elm-keyboard-shortcut#2]
I am listening for the Space shortcut using:

```elm
Shortcut.simpleShortcut Shortcut.Space PlayPauseShortcut
```

But it was not working. After inspecting the companion javascript, it turns out that it checks ```event.key``` and tries to match it with the keyword "Space". The problem is that the ```event.key``` contains " " whereas the ```event.code``` contains the expected "Space". 

I managed to fix this in my code by using a workaround:

```elm
Shortcut.simpleShortcut Shortcut.Space (PlayPauseShortcut)
    , Shortcut.simpleShortcut (Regular " ") (PlayPauseShortcut)
```

But of course it would be good if the package would take the possibility into account.

Thanks for the excellent library!

**Comment by leojpod** [comment]
oh thanks for spotting that! 
I thought I'd checked the space :) 
I'll have a look this week, I'll keep you posted :+1:

**Comment by leojpod** [comment]
The new version should take care of it :)
